function GAEvent(strTrackingID, strUserID, strClientUUID, varargin)

% GAEvent: FUNCTION - Send an 'event' hit type to Google Analytics
%
% Usage: GAEvent(strTrackingID, strUserID, strClientUUID, ...
%                < strEventCategory, strEventAction, strEventLabel, nEventValue, ...
%                strDataSource, strSessionControl, bNonInteractive >)

GACollect(strTrackingID, 'event', strUserID, strClientUUID, ...
   [], [], [], [], ...
   [], [], [], ...
   varargin{:});